/* 建库时字符编码选择utf8mb4 */

/* 用户表 */
CREATE TABLE USER
(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_NAME VARCHAR(16) NOT NULL,
NICKNAME VARCHAR(32) NOT NULL,
PASSWORD VARCHAR(128) NOT NULL,
PHONE VARCHAR(32),
BIRTH_DATE VARCHAR(16),
SEX VARCHAR(4),
ADDRESS VARCHAR(128),
IMAGE_URL VARCHAR(256)
);

/* 发布表 */
CREATE TABLE POST
(
POST_ID INT AUTO_INCREMENT PRIMARY KEY,
USER_ID INT NOT NULL,
UP_TIME VARCHAR(32) NOT NULL,
EDIT_TIME VARCHAR(32) NOT NULL,
TITLE VARCHAR(32) NOT NULL,
CONTENT VARCHAR(1000) NOT NULL,
TAGS VARCHAR(64),
STATUS VARCHAR(4) NOT NULL,
PRICE NUMERIC(14,2) NOT NULL,
ADDRESS VARCHAR(128) NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

/* 评论表 */
CREATE TABLE COMMENT
(
COMMENT_ID VARCHAR(128) PRIMARY KEY,
POST_ID INT NOT NULL,
UP_TIME VARCHAR(32) NOT NULL,
CONTENT VARCHAR(256) NOT NULL,
USER_ID INT NOT NULL,
FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

/* 媒体链接表 */
CREATE TABLE MEDIA_LINK
(
MEDIA_ID VARCHAR(128) PRIMARY KEY,
POST_ID INT NOT NULL,
RES_TYPE VARCHAR(32) NOT NULL,
RES_URI VARCHAR(256) NOT NULL,
FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID)
);

/* 添加第一个用户 */
INSERT INTO USER (USER_ID,USER_NAME,NICKNAME,PASSWORD)
VALUES(1,'zzz','Z19杂货铺',/*'z19'*/'9c2b72aaff10c09a072b1a16d44251fc');